version: '3.7'

services:
  personal-site:
    image: nginx:latest
    container_name: personal-site
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.personal-site-secure.entrypoints=websecure"
      - "traefik.http.routers.personal-site-secure.rule=Host(`dnlk.me`)"
      - "traefik.http.routers.personal-site-secure.middlewares=user-auth@file"

networks:
  proxy:
    external: true

